#  Copyright (c) 2019 Exotic Matter SAS. All rights reserved.
#  Licensed under the BSL License. See LICENSE in the project root for license information.

# Generated by Django 2.2.5 on 2019-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_ftl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fido2state',
            name='domain',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
