version: "2"

services:
  web:
    image: exoticmatter/paper-matter-app
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    user: 1000:1000
    environment:
      ENABLE_WEB: "true"
      # WARNING: NOT SECURE FOR PRODUCTION
      # ===================================
      # For production use, additional ENV variables have to be defined to update default security settings.
      # Please read SELFHOSTING.md
    volumes:
      - "docs:/app/uploads"

  worker:
    image: exoticmatter/paper-matter-app
    restart: always
    depends_on:
      - postgres
      - redis
    user: 1000:1000
    environment:
      ENABLE_WORKER: "true"
      NB_WORKERS: '1'
      ENABLE_CRON: "true"
      # WARNING: NOT SECURE FOR PRODUCTION
      # ===================================
      # For production use, additional ENV variables have to be defined to update default security settings.
      # Please read SELFHOSTING.md
    volumes:
      - "docs:/app/uploads"

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:4-alpine
    restart: always

volumes:
  dbdata:
  docs:
