#  Copyright (c) 2021 Exotic Matter SAS. All rights reserved.
#  Licensed under the Business Source License. See LICENSE in the project root for more information.
import json
import os
import sys
import time


def check():
    """
    Check browser logs generated by ftests.pages.base_page.BasePage#_save_browser_logs (Chrome only)
    Used by CI check-browser-logs job
    Return an error exit code if there is more logs than expected in the tests or or logs differ from the expected ones
    """
    browser_logs_full_report = {}
    tests_with_more_logs = []
    tests_with_less_logs = []
    tests_with_different_logs = {}

    for item in os.scandir(os.path.join("..", "browser_logs")):
        if item.name.endswith(".json"):
            with open(item.path, "r") as f:
                file_content = json.loads(f.read())

            test_path = item.name.split("-")[0]
            browser_logs_full_report[test_path] = {
                "expected": file_content["expected"],
                "actual": file_content["actual"],
            }

            if len(file_content["actual"]) > len(file_content["expected"]):
                tests_with_more_logs.append(test_path)
            elif len(file_content["actual"]) < len(file_content["expected"]):
                tests_with_less_logs.append(test_path)
            else:
                match_errors = []
                for i, actual_log in enumerate(file_content["actual"]):
                    expected_log = file_content["actual"][i]
                    if actual_log["level"] != expected_log["level"]:
                        match_errors.append(
                            f"Log {i + 1}: actual log level ({actual_log['level']}) differ from expected"
                            f" one ({expected_log['level']})"
                        )
                    if actual_log["source"] != expected_log["source"]:
                        match_errors.append(
                            f"Log {i + 1}: actual log source ({actual_log['source']}) differ from"
                            f" expected one ({expected_log['source']})"
                        )
                    if expected_log["message"] not in actual_log["message"]:
                        match_errors.append(
                            f"Log {i + 1}: expected log message not found in actual one"
                        )
                        match_errors.append(f"Expected: {expected_log['message']}")
                        match_errors.append(f"Actual: {actual_log['message']}")

                if len(match_errors):
                    tests_with_different_logs[test_path] = match_errors

    # Display full report
    print(json.dumps(browser_logs_full_report, indent=4))

    # Display non error message
    tests_with_less_logs_count = len(tests_with_less_logs)
    info_message = ""
    if tests_with_less_logs_count:
        info_message += f"\nINFO:\n"
        info_message += (
            f"{tests_with_less_logs_count} Ftest(s) get less logs than expected:\n"
        )
        info_message += f"-------------------------------------------\n"
        info_message += json.dumps(tests_with_less_logs, indent=4)

    # Display success or error message
    error_message = None
    tests_with_logs_count = len(browser_logs_full_report.items())
    tests_with_more_logs_count = len(tests_with_more_logs)
    tests_with_different_logs_count = len(tests_with_different_logs.items())

    if tests_with_more_logs_count or tests_with_different_logs_count:
        error_message = f"\nCHECK FAILED for {tests_with_more_logs_count + tests_with_different_logs_count} Ftest(s):\n"
        error_message += "===========================\n"
        if tests_with_more_logs_count:
            error_message += (
                f"{tests_with_more_logs_count} Ftest(s) get more logs than expected:\n"
            )
            error_message += f"--------------------------------------\n"
            error_message += json.dumps(tests_with_more_logs, indent=4)
        if tests_with_different_logs_count:
            error_message += f"\n{tests_with_different_logs_count} Ftest(s) get different logs than the ones expected:\n"
            error_message += f"----------------------------------------------------\n"
            error_message += json.dumps(tests_with_different_logs, indent=4)
    else:
        if tests_with_logs_count:
            info_message += f"\nCHECK SUCCEEDED for {len(browser_logs_full_report.items())} Ftests: all browser logs were expected"
        else:
            info_message += (
                "\nCHECK SUCCEEDED, no browser logs were produced during Ftests."
            )

    time.sleep(0.5)  # to be sure sys.exit message appears after report print
    if info_message:
        print(info_message)
    sys.exit(error_message)


if __name__ == "__main__":
    check()
