# Generated by Django 2.1.6 on 2019-03-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftlfolder',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.FTLOrg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ftldocument',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
