# Generated by Django 2.2.5 on 2019-12-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191031_2127'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ftlfolder',
            name='folder_name_unique_for_org_level',
        ),
        migrations.AddConstraint(
            model_name='ftlfolder',
            constraint=models.UniqueConstraint(fields=('name', 'parent_id', 'org_id'), name='folder_name_unique_for_org_level'),
        ),
    ]
