# Generated by Django 2.1.6 on 2019-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190324_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
