# Generated by Django 2.1.7 on 2019-03-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mptt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftluser',
            old_name='ftl_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ftlorg',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
