#  Copyright (c) 2020 Exotic Matter SAS. All rights reserved.
#  Licensed under the Business Source License. See LICENSE at project root for more information.

# Generated by Django 2.2.9 on 2020-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20191207_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftldocument",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
