# Generated by Django 2.1.7 on 2019-03-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftlfolder',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.FTLOrg'),
            preserve_default=False,
        ),
    ]
