# Generated by Django 2.2 on 2019-04-01 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190401_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftlfolder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
