# Generated by Django 2.1.7 on 2019-04-06 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ftlfolder_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftldocument',
            name='binary',
            field=models.FileField(max_length=256, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ftldocument',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
