# Generated by Django 2.1.7 on 2019-03-11 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ftlfolder_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftlfolder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
