#  Copyright (c) 2020 Exotic Matter SAS. All rights reserved.
#  Licensed under the BSL License. See LICENSE in the project root for license information.

# Generated by Django 2.2.9 on 2020-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200110_1346"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftldocument",
            name="ocrized",
            field=models.BooleanField(default=False),
        ),
    ]
