# Generated by Django 2.1.7 on 2019-04-08 15:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190406_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftldocument',
            name='binary',
            field=models.FileField(max_length=256, null=True, upload_to=core.models._get_name_binary),
        ),
    ]
