# Generated by Django 2.2 on 2019-04-26 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190408_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftldocument',
            name='ftl_folder',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.FTLFolder'),
        ),
        migrations.AlterField(
            model_name='ftldocument',
            name='ftl_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ftldocument',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FTLOrg'),
        ),
    ]
