# Generated by Django 2.2.10 on 2020-02-19 10:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ftldocument_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftldocument',
            name='ocr_retry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ftldocument',
            name='thumbnail_binary',
            field=models.FileField(max_length=256, null=True, upload_to=core.models._get_name_thumb),
        ),
    ]
