# Generated by Django 2.2 on 2019-05-04 15:49

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190426_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftldocument',
            name='content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ftldocument',
            name='tsvector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
    ]
