# Generated by Django 2.2.11 on 2020-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20200219_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftldocument",
            name="type",
            field=models.CharField(default="application/pdf", max_length=255),
        ),
    ]
