# Generated by Django 2.2.1 on 2019-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190504_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftldocument',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
