# Generated by Django 2.2.1 on 2019-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ftldocument_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftldocument',
            name='language',
            field=models.CharField(default='english', max_length=64),
        ),
    ]
