# Generated by Django 2.2.11 on 2020-04-28 15:23

import django.core.validators
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_ftlorg_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftlorg",
            name="slug",
            field=models.SlugField(
                max_length=128, unique=True, validators=[core.models.org_hash_validator]
            ),
        ),
        migrations.AlterField(
            model_name="ftluser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(),
                    core.models.email_hash_validator,
                ],
                verbose_name="email address",
            ),
        ),
    ]
