# Generated by Django 2.2.1 on 2019-05-17 23:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190514_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftldocument',
            name='thumbnail_binary',
            field=models.FileField(max_length=256, null=True, upload_to=core.models._get_name_binary),
        ),
    ]
