# Generated by Django 2.2.16 on 2020-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_ftldocumentsharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftluser",
            name="lang",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="ftluser",
            name="tz",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
