# Generated by Django 2.2 on 2019-07-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ftldocument_thumbnail_binary'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ftlfolder',
            constraint=models.UniqueConstraint(fields=('name', 'level', 'org_id'), name='folder_name_unique_for_org_level'),
        ),
    ]
