# Generated by Django 2.2.2 on 2019-06-29 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ftldocument_thumbnail_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftldocument',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
