# Generated by Django 2.2.16 on 2020-12-23 09:15

from django.db import migrations

from core.ftl_migration_tool import clean_user_permission


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20201223_1015"),
    ]

    operations = [
        migrations.RunPython(
            clean_user_permission, reverse_code=migrations.RunPython.noop
        ),
    ]
