# Generated by Django 2.2 on 2019-07-17 14:59

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_citext_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftlfolder',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=128),
        ),
    ]
