# Generated by Django 2.2.2 on 2019-07-24 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190717_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftldocument',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
