# Generated by Django 2.2.4 on 2019-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190724_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftldocument',
            name='count_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
