# Generated by Django 2.2.4 on 2019-08-21 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ftldocument_count_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftldocument',
            name='pid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='ftldocument',
            index=models.Index(fields=['org', 'pid'], name='core_ftldoc_org_id_7dd81f_idx'),
        ),
        migrations.AddIndex(
            model_name='ftldocument',
            index=models.Index(fields=['org', 'ftl_folder'], name='core_ftldoc_org_id_891978_idx'),
        ),
    ]
